version: '3.7'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.19-arm64
    command:
      - etcd
      - --name=etcd
      - --data-dir=/data
      - --advertise-client-urls=http://etcd:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd=http://etcd:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=Be0uNUOG1mxJAThWTQnHLA==
    volumes:
      - etcd:/data
    networks:
      - stolon
    environment:
      ETCD_UNSUPPORTED_ARCH: arm64
    ports:
      - 2379:2379

  keeper:
    image: mybackspace/stolon:master-pg14
    hostname: keeper-0
    networks:
      - stolon
    build:
      context: .
    command:
      - /bin/bash
      - -ce
      - |
        _id="$${HOSTNAME##*-}"
        _cmd="/usr/local/bin/stolon-keeper"
        if [ $$(id -u) -eq 0 ]; then
            _cmd="/usr/local/bin/gosu stolon $${_cmd}"
        fi

        if [ "$${_id}" -eq 0 ] && [ ! -d "/stolon/data/postgres/base" ]; then
            stolonctl init -y --log-level=debug
            stolonctl update -p -f <(cat /data/config.json)
        fi

        $${_cmd} --uid "$${_id}" --log-level info
    volumes:
      - ./db-data:/stolon/data
      - ./examples/compose:/data
    ports:
      - 8888:8080
    environment:
      STKEEPER_PG_REPL_USERNAME: repluser
      STKEEPER_PG_SU_USERNAME: stolon
      STKEEPER_METRICS_LISTEN_ADDRESS: 0.0.0.0:8080
      STKEEPER_PG_SU_PASSWORDFILE: /data/password
      STKEEPER_PG_REPL_PASSWORDFILE: /data/replpassword
      STOLONCTL_CLUSTER_NAME: stolon-cluster
      STOLONCTL_STORE_BACKEND: etcdv3
      STOLONCTL_STORE_ENDPOINTS: http://etcd:2379
      PG_HOST: proxy
      STKEEPER_CLUSTER_NAME: stolon-cluster
      STKEEPER_STORE_BACKEND: etcdv3
      STKEEPER_STORE_ENDPOINTS: http://etcd:2379
      STKEEPER_PG_LISTEN_ADDRESS: keeper
      STKEEPER_DATA_DIR: /stolon/data
    depends_on:
      - etcd
      - proxy
      - sentinel

  proxy:
    image: mybackspace/stolon:master-pg14
    networks:
      - stolon
    build:
      context: .
    command:
      - /usr/local/bin/stolon-proxy
    ports:
      - 5432:5432
    environment:
      STPROXY_CLUSTER_NAME: stolon-cluster
      STPROXY_STORE_BACKEND: etcdv3
      STPROXY_STORE_ENDPOINTS: http://etcd:2379
      STPROXY_LISTEN_ADDRESS: 0.0.0.0

  sentinel:
    image: mybackspace/stolon:master-pg14
    networks:
      - stolon
    build:
      context: .
    command:
      - /usr/local/bin/stolon-sentinel
    environment:
      STSENTINEL_CLUSTER_NAME: stolon-cluster
      STSENTINEL_STORE_BACKEND: etcdv3
      STSENTINEL_STORE_ENDPOINTS: http://etcd:2379


volumes:
  etcd:

networks:
  stolon:
