apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.proxyName" . }}
  labels:
    component: stolon-proxy
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    - port: {{ .Values.proxy.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    component: stolon-proxy
    stolon-cluster: {{ include "stolon.clusterName" . }}
