{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "stolon.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "stolon.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "stolon.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
