apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.fullname" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.stolon.postgresPassword | default (randAlphaNum 30) | b64enc }}
  replpassword: {{ .Values.stolon.replicationPassword | default (randAlphaNum 30) | b64enc }}
  {{- with .Values.stolon.additionalUsers }}
  {{- range . }}
  user-{{ .name }}: {{ default (randAlphaNum 30) .password | b64enc }}
  {{- end }}
  {{- end }}
