apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.sentinelName" . }}
  labels:
    component: stolon-sentinel
    {{- include "stolon.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sentinel.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    component: stolon-sentinel
    stolon-cluster: {{ include "stolon.clusterName" . }}
